---
title: "Untitled"
author: "Gertjan Verhoeven"
date: '2022-07-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

df <- read.csv("tableau_downloads/Race Success and Popularity (2)_Full Data_data.csv")
```

```{r}
head(df)

df$Date <- as.Date(df$Date, "%m/%d/%Y")

df$Rank_bin <- cut(df$Rank, breaks = c(-Inf, 120, 130, 140, 150, 160, 170, 180, 190, Inf))
```

```{r}
tourney_loc <- df %>% 
  filter(Nation != "" & Tournament.Id != "") %>%
  group_by(Tournament.Id, Nation) %>%
  summarise(n_games_by_nations = n()) %>%
  slice_max(n_games_by_nations, n = 1, with_ties = FALSE) %>%
  rename(Tournament.Country = Nation)

df <- df %>%
  left_join(tourney_loc, by = "Tournament.Id")
```


```{r}
res <- df %>% 
  group_by(Tournament.Id, Tournament.Name, Tournament.Country) %>%
  summarise(n = n(), date = min(Date), n_coaches = n_distinct(Coach))
```

```{r fig.width = 10, fig.height = 12}
ggplot(res, aes(x = date, y = n_coaches, label = Tournament.Name)) +
  geom_point() +
  geom_label() +
  expand_limits(y=0) + 
  facet_wrap(~Tournament.Country, ncol = 5, scales = "free_y")
```
```{r}
df %>% 
  group_by(Result, TDs.Net, Wins) %>%
  summarise(n())
```
```{r}
df %>% 
  filter(Rank < 180) %>%
  group_by(Race) %>%
  summarise(perc_win = mean(Wins), n()) %>%
  arrange(-perc_win)
```
```{r}
df %>% 
  filter(Race == "High Elf") %>%
  group_by(Rank_bin) %>%
  summarise(perc_win = mean(Wins), n()) %>%
  arrange(-Rank_bin)
```
```{r}
df %>% 
  filter(Race == "Orc") %>%
  group_by(Rank_bin) %>%
  summarise(perc_win = mean(Wins), n()) %>%
  arrange(-Rank_bin)
```


```{r}
df %>% 
  filter(Race == "Wood Elf") %>%
  group_by(Rank_bin) %>%
  summarise(perc_win = mean(Wins), n()) %>%
  arrange(-Rank_bin)
```


```{r}
df %>% 
  filter(Race == "High Elf" & Rank >= 190) %>%
  group_by(Coach, Nation, Tournament.Name) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-n)
```



```{r}
df %>% 
  filter(Race == "High Elf") %>%
  group_by(Tournament.Name) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  mutate(label2 = ifelse(n > 10, Tournament.Name, NA)) %>%
  arrange(-n) %>%
  ggplot(aes(x = n, y = perc_win, label = label2)) + 
  geom_point() +
  geom_label()
```

```{r}
df %>% 
  filter(Race == "High Elf") %>%
  group_by(Tournament.Name) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-n)
```


This tournament used Eurobowl 2022 rules. Under those rules, high elves are Tier 4. 

https://web.archive.org/web/20220217093712/http://hammabowl.de/turnierinfos-2


```{r}
df %>% 
  filter(Tournament.Name =="HammaBowl V") %>%
  group_by(Tournament.Country, Coach, Race) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-perc_win)
```


```{r}
df %>% 
  filter(Tournament.Name =="UK Team Challenge VII") %>%
  group_by(Tournament.Country, Coach, Race) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-perc_win)
```
```{r}
df %>% 
  filter(Tournament.Name =="UK Team Challenge VII") %>%
  group_by(Race) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-perc_win)
```

Also here High Elf are in a low tier, allowing more skills.

https://www.bbuktc.com/rules/

Tournament in Lyon, also using Euroopen rules. So High Elves tier 4 and access to Star players.

http://teamfrancebb.1fr1.net/t7449-la-coupe-des-voraces-iv-16-17-avril-2022


```{r}
df %>% 
  filter(Tournament.Name =="Coupe des voraces 4") %>%
  group_by(Coach, Race) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-perc_win)
```
```{r}
df %>% 
  filter(Tournament.Name =="Coupe des voraces 4")
```
```{r}
df$eurobowl_rulepack1 <- grepl("[Mm]alta", df$Description)
df$eurobowl_rulepack2 <- grepl("[Ee]urobowl", df$Description)
df$eurobowl_rulepack3 <- grepl("[Ee]ur[oO]pen", df$Description)

df$eurobowl_rulepack <- with(df, eurobowl_rulepack1 + eurobowl_rulepack2 + eurobowl_rulepack3)
```

```{r}
table(df$eurobowl_rulepack)
```
```{r}
df %>% 
  filter(eurobowl_rulepack > 0) %>%
  group_by(Race) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-perc_win)
```
```{r}
df %>% 
  filter(eurobowl_rulepack > 0) %>%
  group_by(Tournament.Name) %>%
  summarise(n = n()) %>%
  arrange(-n)

```

```{r}
df %>% 
  group_by(Race) %>%
  summarise(perc_win = mean(Wins), n = n()) %>%
  arrange(-perc_win) %>%
  filter(n > 100) %>%
  ggplot(aes(x = n, y = perc_win, label = Race )) +
  geom_point() +
  geom_label()
```


# Eurobowl team rosters

```{r}
library(tidyverse)

eb_df <- read.csv("tableau_downloads/eurobowl_rosters/Races_Full Data_data.csv")
eb_df$Full.Path <- NULL

eb_df <- eb_df %>% 
  filter(Tournament == "Eurobowl") %>% 
  arrange(File, Race) %>% 
  filter(Country != "")
```

Check that we have 24 x 8 = 192 rosters:

```{r}
eb_df %>%
  group_by(Coach, Country) %>%
  summarise(n = n()) %>% arrange(Country)
```

Reproduceer top races:

```{r}
res <- eb_df %>%
  group_by(Coach, Race) %>%
  summarise(n = n()) %>% 
  group_by(Race) %>%
  summarise(cnt = n()) %>%
  arrange(-cnt)

ggplot(res, aes(x = reorder(Race, cnt), y = cnt)) +
  geom_point() +
  expand_limits(y = 0) +
  coord_flip()
```

```{r}
races <- unique(eb_df$Race)

for(i in 1:length(races)){
  
  df <- eb_df %>% 
    filter(Type == "Players" & Race == races[i]) %>%
    group_by(Description, Coach, Country) %>%
    summarise(n = n())
  
  gp <- ggplot(df, aes(x = Country, y = Description)) +
    geom_tile(aes(fill = n), color = "black") +
    geom_text(aes(label = n), color = "white") +
    scale_fill_gradient(low = "light blue", high = "blue", na.value = "white") +
    coord_fixed() +
    theme(legend.position = "none") +
    ggtitle(paste0("Eurobowl 2022 " , races[i], " rosters")) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    theme(panel.background = element_rect(fill = "white"))
  print(gp)
}
```
# PM toevoegen historische landen ranking 2019
